[build-system]
requires = ["setuptools >= 77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aiohttp_socks"
license = "Apache-2.0"
description = "Proxy connector for aiohttp"
readme = "README.md"
authors = [{ name = "Roman Snegirev", email = "snegiryev@gmail.com" }]
keywords = ["asyncio", "aiohttp", "socks", "socks5", "socks4", "http", "proxy"]
requires-python = ">=3.9.0"

dynamic = ["version"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: MacOS",
    "Operating System :: Microsoft",
    "Operating System :: POSIX :: Linux",
    "Topic :: Internet :: WWW/HTTP",
    "Intended Audience :: Developers",
    "Framework :: AsyncIO",
]

dependencies = ["aiohttp>=3.10.0", "python-socks[asyncio]>=2.4.3,<4.0.0"]

[dependency-groups]
dev = [
    "anyio>=4.12.1",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-cov>=7.1.0",
    "tiny-proxy>=0.3.0",
    "trustme>=1.2.1",
    "starlette>=0.49.3",
    "uvicorn>=0.39.0",
    "yarl>=1.22.0",
    "mypy>=1.19.1",
    "ruff>=0.16.1",
]

[project.urls]
homepage = "https://github.com/romis2012/aiohttp-socks"
repository = "https://github.com/romis2012/aiohttp-socks"

[tool.setuptools.dynamic]
version = { attr = "aiohttp_socks.__version__" }

[tool.setuptools.packages.find]
include = ["aiohttp_socks*"]

[tool.pytest.ini_options]
asyncio_mode = "strict"


[tool.mypy]
allow_redefinition = true
disable_error_code = ["import-untyped", "no-redef"]

[tool.ruff]
line-length = 89
indent-width = 4

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",
    "TD",
    "CPY001", # missing-copyright-notice (CPY001)
    "ANN401", # any-type (ANN401)
    "FA100",  # future-rewritable-type-annotation (FA100)
    "S101",   # assert (S101)
    "COM812", # missing-trailing-comma (COM812),
    "TRY003", # raise-vanilla-args (TRY003)
    "EM101",  # raw-string-in-exception (EM101)
    "EM102",  # f-string-in-exception (EM102)
    "RET504", # unnecessary-assign (RET504)
    "ERA001", # commented-out-code (ERA001)
    "TC001",  # typing-only-first-party-import (TC001)
    "TC002",  # typing-only-third-party-import (TC002)
    "TC003",  # typing-only-standard-library-import (TC003)
]
fixable = ["ALL"]
unfixable = [
    "RET505", # superfluous-else-return (RET505)
]
[tool.ruff.lint.pylint]
max-args = 8

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "PLR2004", # magic-value-comparison (PLR2004)
    "PT011",   # pytest-raises-too-broad (PT011)
    "C416",    # unnecessary-comprehension (C416)
    "T201",    # print (T201)
    "PT007",   # pytest-parametrize-values-wrong-type (PT007)
    "FBT001",  # boolean-type-hint-positional-argument (FBT001)
]
